// Headless test of the manager-inquiry block (v3.12.0+). Run: tests/run.sh
let appended=null;
global.fetch=()=>Promise.resolve({json:()=>Promise.resolve({})});
global.alert=m=>{throw new Error("ALERT: "+m)};
const mkEl=()=>({style:{},innerHTML:"",textContent:"",value:"",checked:false,remove(){},onclick:null});
global.document={createElement:()=>mkEl(),getElementById:()=>null,body:{appendChild:e=>{appended=e}},querySelector:()=>null};
global.el=()=>mkEl();
const S={sel:new Set(),mgr:{}};global.S=S;
let ROWS=[];global.getF=()=>ROWS;global.vKey=v=>(v.imo||v.name);
eval(require('fs').readFileSync(process.argv[2],'utf8'));
let pass=0,fail=0;const t=(n,c,x)=>{c?pass++:fail++;console.log((c?"  ok   ":"  FAIL ")+n+(c?"":"  <<"+x+">>"))};
console.log("-- fmtDay --");
t("ISO -> '18 September'",fmtDay("2026-09-18T14:00")==="18 September",fmtDay("2026-09-18T14:00"));
t("empty -> TBC",fmtDay("")==="TBC");t("garbage -> TBC",fmtDay("not a date")==="TBC");
t("Jan boundary",fmtDay("2026-01-01T00:00")==="1 January");t("Dec boundary",fmtDay("2026-12-31T23:59")==="31 December");
console.log("-- mgrBody: single vessel --");
const v1={name:"FURNESS VICTORIA",imo:"9640621",portName:"Gijón",etaISO:"2026-09-18T08:00",flagCode:"PA"};
const b1=mgrBody([v1],"");
t("salutation defaults to Dear Sirs",b1.startsWith("Dear Sirs,"));
t("matches his sentence",b1.includes("I understand FURNESS VICTORIA (IMO 9640621) is due in Gijón on 18 September."));
t("singular 'while she's in port'",b1.includes("while she's in port"));
t("keeps the authority line",b1.includes("authorised by Liberia, the Marshall Islands and Malta"));
t("quotation line",b1.includes("Happy to send a quotation"));
t("signature title",b1.includes("Flag State Inspector / Auditor"));
t("signature contact",b1.includes("info@ironsea.es · +34 603 730 040 (WhatsApp)"));
t("no stale 'Iron Sea' branding",!b1.includes("| Iron Sea"));t("no flag list in signature",!b1.includes("LISCR ·"));
console.log("-- mgrBody: named contact + multi-vessel --");
t("named salutation",mgrBody([v1],"Dr. Mittal").startsWith("Dear Dr. Mittal,"));
const v2={name:"CAPE CORFU",imo:"9857432",portName:"Vigo",etaISO:"2026-09-20T22:00",flagCode:"LR"};
const b2=mgrBody([v1,v2],"");
t("plural 'while they are in port'",b2.includes("while they are in port"));
t("lists both vessels",b2.includes("• FURNESS VICTORIA (IMO 9640621) — Gijón — 18 September")&&b2.includes("• CAPE CORFU (IMO 9857432) — Vigo — 20 September"));
t("multi uses list lead-in",b2.includes("the following vessels under your management"));
console.log("-- subject --");
t("single subject",mgrSubject([v1])==="Pre-PSC inspection / ISM internal audit — FURNESS VICTORIA, Gijón, 18 September",mgrSubject([v1]));
t("multi subject",mgrSubject([v1,v2])==="Pre-PSC inspection / ISM internal audit — 2 vessels, northern Spain");
console.log("-- grouping via genManagerInquiry --");
const v3={name:"SEA EAGLE",imo:"9111111",portName:"Bilbao",etaISO:"2026-09-19T06:00",flagCode:"MT"};
ROWS=[v1,v2,v3];
S.mgr={"9640621":{ism:"Viridian Maritime Pte Ltd",ismEmail:"enquiries@viridianmaritime.com",verified:false,source:"magicport",phone:"+65 6371 7711",notes:"note text"},
       "9857432":{ism:"Viridian Maritime Pte Ltd",ismEmail:"enquiries@viridianmaritime.com",verified:false,source:"magicport"}};
S.sel=new Set(["9640621","9857432","9111111"]);
genManagerInquiry();const h=appended.innerHTML;
t("2 groups from 3 vessels (same manager merged)",h.includes("1 of 2 with a manager on file"),(h.match(/\d+ of \d+ with a manager on file/)||[])[0]);
t("known manager card rendered",h.includes("🏢 Viridian Maritime Pte Ltd — 2 vessel(s)"));
t("unverified badge shown",h.includes("⚠ unverified (magicport)"));
t("phone shown (v3.13.0)",h.includes("☎ +65 6371 7711"));
t("notes shown (v3.13.0)",h.includes("note text"));
t("unknown-manager card for SEA EAGLE",h.includes("❓ Manager unknown — SEA EAGLE"));
t("lookup link uses the ISM manager query",h.includes("ISM+manager"));
t("Equasis link present for known IMO",h.includes("P_IMO=9111111"));
t("save form rendered for unknown",h.includes('id="mi_ism_'));
t("conflict warning names the LR vessel",h.includes("CAPE CORFU (LR)"));
t("conflict warning does NOT name the PA vessel",!h.includes("FURNESS VICTORIA (PA)"));
t("both groups warn (LR in one, MT in other)",(h.match(/you hold FSI authority/g)||[]).length===2);
t("MT vessel named in its own warning",h.includes("SEA EAGLE (MT)"));
t("mailto built for known manager",h.includes("mailto:enquiries@viridianmaritime.com"));
t("log button present",h.includes("miLog("));
console.log("-- v3.14.0: known manager, no email --");
S.mgr={"9111111":{ism:"Anglo-Eastern Ship Management",ismEmail:"",verified:false,source:"magicport-auto"}};S.sel=new Set(["9111111"]);genManagerInquiry();
const h2=appended.innerHTML;
t("shows 'no email on file'",h2.includes("no email on file"));
t("find-contact link present",h2.includes("contact+DPA+email")||h2.includes("contact%20DPA%20email"));
t("no mailto when no email",!h2.includes("mailto:"));
console.log("");console.log(pass+" passed, "+fail+" failed");process.exit(fail?1:0);
